# Generated by Django 3.1.7 on 2021-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210317_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
